export const RESEARCH_REQUEST = 'RESEARCH_REQUEST'
export const RESEARCH_SUCCESS = 'RESEARCH_SUCCESS'
export const RESEARCH_FAIL = 'RESEARCH_FAIL'

export const RESEARCHS_REQUEST = 'RESEARCHS_REQUEST'
export const RESEARCHS_SUCCESS = 'RESEARCHS_SUCCESS'
export const RESEARCHS_FAIL = 'RESEARCHS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
