export const SESSION_REQUEST = 'SESSION_REQUEST'
export const SESSION_SUCCESS = 'SESSION_SUCCESS'
export const SESSION_FAIL = 'SESSION_FAIL'

export const SESSIONS_REQUEST = 'SESSIONS_REQUEST'
export const SESSIONS_SUCCESS = 'SESSIONS_SUCCESS'
export const SESSIONS_FAIL = 'SESSIONS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
